spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url:jdbc:postgresql://localhost:5432/postgres?createDatebaseIfNotExist=true