package com.example.blogs.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.blogs.RequestDto.BlogRequestDto;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.util.Optional;
import java.util.UUID;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = "Blog")
public class Blog {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String uuid;

    @DynamoDBAttribute(attributeName = "title")
    @DynamoDBRangeKey
    private String title;

    @DynamoDBAttribute(attributeName = "content")
    private String content;



    public Blog(String title){
        this.title=title;
    }
    public static Blog fromModel(BlogRequestDto blog) {
        return Blog
                .builder()
                .uuid(blog.getUuid())
                .title(blog.getTitle())
                .content(blog.getContent())
                .build();
    }

    public static BlogRequestDto toModel(Blog blog) {
        return BlogRequestDto
                .builder()
                .uuid(blog.uuid)
                .title(blog.title)
                .content(blog.content)
                .build();
    }


}
